<?php

namespace Exan\Dhp\Const;

class Events
{
    final const RAW = 'RAW';
    final const READY = 'READY';

    final const APPLICATION_COMMAND_PERMISSIONS_UPDATE = 'APPLICATION_COMMAND_PERMISSIONS_UPDATE';
    final const AUTO_MODERATION_RULE_CREATE = 'AUTO_MODERATION_RULE_CREATE';
    final const AUTO_MODERATION_RULE_UPDATE = 'AUTO_MODERATION_RULE_UPDATE';
    final const AUTO_MODERATION_RULE_DELETE = 'AUTO_MODERATION_RULE_DELETE';
    final const AUTO_MODERATION_ACTION_EXECUTION = 'AUTO_MODERATION_ACTION_EXECUTION';

    final const CHANNEL_CREATE = 'CHANNEL_CREATE';
    final const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
    final const CHANNEL_DELETE = 'CHANNEL_DELETE';
    final const CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE';

    final const THREAD_CREATE = 'THREAD_CREATE';
    final const THREAD_UPDATE = 'THREAD_UPDATE';
    final const THREAD_DELETE = 'THREAD_DELETE';
    final const THREAD_LIST_SYNC = 'THREAD_LIST_SYNC';
    final const THREAD_MEMBER_UPDATE = 'THREAD_MEMBER_UPDATE';
    final const THREAD_MEMBERS_UPDATE = 'THREAD_MEMBERS_UPDATE';

    final const GUILD_CREATE = 'GUILD_CREATE';
    final const GUILD_UPDATE = 'GUILD_UPDATE';
    final const GUILD_DELETE = 'GUILD_DELETE';

    final const GUILD_BAN_ADD = 'GUILD_BAN_ADD';
    final const GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE';

    final const GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE';
    final const GUILD_STICKERS_UPDATE = 'GUILD_STICKERS_UPDATE';

    final const GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE';

    final const GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD';
    final const GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE';
    final const GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE';
    final const GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK';

    final const GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE';
    final const GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE';
    final const GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE';

    final const GUILD_SCHEDULED_EVENT_CREATE = 'GUILD_SCHEDULED_EVENT_CREATE';
    final const GUILD_SCHEDULED_EVENT_UPDATE = 'GUILD_SCHEDULED_EVENT_UPDATE';
    final const GUILD_SCHEDULED_EVENT_DELETE = 'GUILD_SCHEDULED_EVENT_DELETE';
    final const GUILD_SCHEDULED_EVENT_USER_ADD = 'GUILD_SCHEDULED_EVENT_USER_ADD';
    final const GUILD_SCHEDULED_EVENT_USER_REMOVE = 'GUILD_SCHEDULED_EVENT_USER_REMOVE';

    final const INTEGRATION_CREATE = 'INTEGRATION_CREATE';
    final const INTEGRATION_UPDATE = 'INTEGRATION_UPDATE';
    final const INTEGRATION_DELETE = 'INTEGRATION_DELETE';
    final const INTERACTION_CREATE = 'INTERACTION_CREATE';

    final const INVITE_CREATE = 'INVITE_CREATE';
    final const INVITE_DELETE = 'INVITE_DELETE';

    final const MESSAGE_CREATE = 'MESSAGE_CREATE';
    final const MESSAGE_UPDATE = 'MESSAGE_UPDATE';
    final const MESSAGE_DELETE = 'MESSAGE_DELETE';
    final const MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK';
    final const MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD';
    final const MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE';
    final const MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL';
    final const MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI';

    final const PRESENCE_UPDATE = 'PRESENCE_UPDATE';

    final const STAGE_INSTANCE_CREATE = 'STAGE_INSTANCE_CREATE';
    final const STAGE_INSTANCE_UPDATE = 'STAGE_INSTANCE_UPDATE';
    final const STAGE_INSTANCE_DELETE = 'STAGE_INSTANCE_DELETE';

    final const TYPING_START = 'TYPING_START';
    final const USER_UPDATE = 'USER_UPDATE';

    final const VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE';
    final const VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE';

    final const WEBHOOKS_UPDATE = 'WEBHOOKS_UPDATE';
}
